variables:
  DOCKER_DRIVER: overlay2 # use faster volume driver
  DOCKER_IMAGE: registry.gitlab.com/publicmarket/open-inventory

stages:
  - build
  - test

build:
  stage: build
  tags:
    - build
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
    # cleanup
    - docker system prune -f

rspec:
  image: $DOCKER_IMAGE:latest
  stage: test
  cache:
    paths:
      - vendor/bundle
  variables:
    RAILS_ENV: test
  script:
    - bundle exec rspec
