default: &default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: storefront_development
  pool: <%= ENV['WEB_THREADS'] || 20 %>
  username: postgres
  password: postgres

test:
  adapter: sqlite3
  database: db/storefront_api.sqlite3

staging:
  <<: *default
  database: storefront_staging
  pool: <%= ENV['WEB_THREADS'] || 20 %>
  username: <%= ENV['DB_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || Rails.application.credentials[:db_password] %>
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  database: storefront_production
  pool: <%= ENV['WEB_THREADS'] || 20 %>
  username: <%= ENV['DB_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || Rails.application.credentials[:db_password] %>
  host: <%= ENV['DB_HOST'] %>
